### ISSUE TITLE
No Rest server name set

### ISSUE THREAD

**Issue by snobear** [xpandgithub/virtualcareernetwork#1]
Hi, I stumbled upon this project and was trying to get it installed in Drupal 7.  Not sure if its still maintained, but figured I'd ask for help here anyway.

After copying the contents of this github project into my drupal install and installing the additional modules, I'm getting:

> No Rest server name set

I see that error comes from `modules/vcngeneral/vcngeneral.module` but I'm not sure how to set the various settings VCN is looking for. Any ideas?

**Comment by xpandgithub** [comment]
As of right now the REST services haven't been opened to the public. So you'd have to set up your own database and REST services on your servers and connect to them.

**Comment by snobear** [comment]
@xpandgithub Do I need REST services to run the VCN website?  Is it a requirement to run the code on this GitHub page?

**Comment by xpandgithub** [comment]
All the career/school type data within VCN comes from our REST services. Everything else is part of a Drupal database. I wouldn't say the REST services are necessarily a requirement but that's where we pull all the career/school information. If you were using the code for your own system you could rewrite it so that all your data was within the Drupal database, which would make it more like a true Drupal system. Our original requirements made it so that we had to have REST services so we are really just using Drupal as a front end and user store.

**Comment by snobear** [comment]
I see, thanks for the replies.  Do you have any docs on what the structure of the DB and/or REST should be?  If not, it sounds like I'd have to really dig into the code to see what it's requesting.

**Comment by xpandgithub** [comment]
Sorry we don't have any docs on the DB structure.
